bin/templates/project/cordova/run
The `run` command in `cordova-browser` was using an old (never released) API for `cordova-serve` (I clearly checked in the wrong version of the code when adding `cordova-serve` support to `cordova-browser`).
=> CB-9350 'cordova run browser' throws an exception.

cordova-js-src/exec.js, cordova-lib/cordova.js
This makes the browser exec methods consistent with other js-only platforms.
CallbackID's are used, callbacks can be 'kept' and missing proxies are logged.
=> CB-9669 Browser exec should have more failsafes

bin/template/cordova/Api.js
manifest.json added to browser during create
=> CB-12804 : manifest.json added to browser during create

bin/template/cordova/lib/clean.js
browser
removes www/ folder during clean
=> CB-11711 clean should destroy platforms/browser/www folder contents

bin/template/cordova/clean.bat
browser ( when run on windows )
adds missing clean.bat file
=> CB-11710 Add missing 'clean.bat' file

bin/template/cordova/lib/build.js, bin/template/cordova/lib/run.js
Fixed issue with cordova run/cordova build not working. 
This requires the latest unreleased `cordova-serve` to work. PR for cordova-serve that is required is at https://github.com/apache/cordova-serve/pull/4
=> CB-13188: fixed issues with run and build scripts

bin/template/cordova/Api.js, bin/template/cordova/browser_parser.js
Browser
Fixes merge directory support. https://issues.apache.org/jira/browse/CB-13435
=> CB-13435: fix merges directory support for browser

bin/template/cordova/browser_handler.js, spec/browser_handler.spec.js
Fixed asset tag when adding push plugin to browser
=> CB-13562 : fixed asset tag when adding push plugin to browser

cordova-js-src/confighelper.js
Browser
Causes xhr that gets the config.xml file to respect the base href (if set) in the index.html
Manual testing
=> CB-13999: (browser) - Reading config.xml respects base href

bin/template/cordova/lib/run.js
Allows to hide console output when launch cordova run browser
=> CB-14252: Allow to send --silent arg to run command to disable output

.travis.yml, appveyor.yml, package.json
browser
- Drop Node 4 Support
- Added Node 10 Support
- `npm run jasmine`
- https://travis-ci.org/erisu/cordova-browser/builds/427072902
=> CB-14073 browser: Drop Node 4, Added Node 10

.gitignore, bin/template/cordova/Api.js, bin/template/cordova/lib/run.js, package.json
browser
This PR contains final preparations for the Cordova 9 release goals. 
See [Cordova 9 Release Plan](https://github.com/apache/cordova/issues/10).
- Bumped Cordova Dependencies
- `cordova-common@^3.1.0`
- `cordova-serve@^3.0.0`
- Bumped ESLint dependencies with correction
- `eslint@^5.12.0`
- `eslint-config-semistandard@^13.0.0`
- `eslint-config-standard@^12.0.0`
- `eslint-plugin-import@^2.14.0`
- `eslint-plugin-node@^8.0.1`
- `eslint-plugin-promise@^4.0.1`
- `eslint-plugin-standard@^4.0.0`
- Bumped Dev Dependencies
- `jasmine@^3.3.1`
- `tmp@0.0.33`
- Updated Dependencies
- `nopt@^4.0.1`
- Added nyc code coverage dependency
- `npm t`
- ESLint
- Jasmine unit testing
- [Travis CI](https://travis-ci.org/erisu/cordova-browser/builds/478166835)
- Platform Add & Prepare
```
$ npx …
```
=> Browser Platform Release Preparation (Cordova 9)

bin/lib/update.js, bin/update
browser
Remove `Q` Efforts: https://github.com/apache/cordova/issues/7
This repo did not have the `Q` dependency defined explicit in `package.json` but was still using `Q` that would have been a sub-dependency of `cordova-common`.
This PR removes the only usage of `Q`.
- `npm t`
- Update with Good Project Path
```
$ ./cordova-browser/bin/update /cordova/projectPath
Removing existing browser platform.
Successfully updated browser project.
```
- Update with Bad Path
```
$ ./cordova-browser/bin/update /cordova/fakepath
Update failed due to CordovaError: Browser platform does not exist here: /cordova/fakepath_
at Object.module.exports.run (/cordova/cordova-browser/bin/lib/update.js:38:31)
at Object.<anonymous> (/cordova/cordova-browser/bin/update:27:12)
at Module._compile …
```
=> Remove Q for Native Promise

package.json
Use current version of `nyc` to resolve a bug that was seen with v13.x on Windows with node >= 10.
Update `nyc` dev dependency
=> chore: update nyc dev dependency

spec/projectApi.spec.js
Replaces the existing test stub for `Api.createPlatform` with a real test that asserts a few things.
This also gets rid of the only instance of `done` in this repo (see https://github.com/apache/cordova/issues/169).
=> Replace test stub for Api.createPlatform

.travis.yml, appveyor.yml
=> ci: removes Node.js v6 and v8 from testing

.eslintrc.yml, bin/create, bin/lib/create.js, bin/template/cordova/Api.js, bin/template/cordova/browser_handler.js, bin/template/cordova/lib/clean.js, bin/template/cordova/lib/run.js, bin/template/cordova/run, cordova-js-src/.eslintrc.yml, cordova-js-src/exec.js, cordova-js-src/platform.js, package.json, spec/.eslintrc.yml, spec/browser_handler.spec.js, spec/create.spec.js, spec/manifest.spec.js, spec/projectApi.spec.js
Use Cordova's ESLint Configs.
https://github.com/apache/cordova/issues/142
- `npm t`
=> breaking: @cordova/eslint-config w/ applied fix

.npmrc
Development Environment
Progresses https://github.com/apache/cordova/issues/299
Adds a npmrc config file to the repo which the `registry` explicitly set to ensure that the official NPM registry is used, particularly for those who may have an alternate NPM registry set.
Ran npm test
=> chore: Added .npmrc

package.json
if we are[ dropping node 14 support](https://github.com/apache/cordova-browser/pull/119) we should update the engines to require node 16
=> chore!: set node engine to >=16.0.0

package-lock.json, package.json
Use latest possible dependencies.
Bumped:
- `cordova-common@5.0.0`
- `cordova-serve@4.0.1`
- `nopt@7.1.0`
- `jasmine@4.6.0`
- `nyc@15.1.0`
- `tmp@0.2.1`
Updated node engine requirement `>=16.13.0` to follow requirements from [`nopt`](https://github.com/npm/nopt/blob/v7.1.0/package.json#L46) & [`abbrev`](https://github.com/npm/abbrev-js/blob/v2.0.0/package.json#L37)
`npm t`
=> dep!: bump all possible dependencies w/ node engine >=16.13.0 requirement
